### ISSUE TITLE
Notify doesn't seem to work?

### ISSUE THREAD

**Issue by dac09** [Urucas/testfairy#4]
Hi,

Thank you for making this first of all - find it easier to use than the official ones.

It seems the --notify flag doesn't seem to have any affect? Either using emails or push notifications?

Also, is there a way you can set what group to notify?

Thanks,
Danny

**Comment by vrunoa** [comment]
Hey @dac09 let me check again If the notify settings is working and if it was possible to select a group, I think it was possible to select a group of testers. I'll give a responde by tonight or tomorrow morning.

**Comment by vrunoa** [comment]
@dac09 the notify param was working but I was missing the ```groups``` param to tell which groups to notify. It's working now, update your cli to the version **0.0.5**. 

Example:
```testfairy --platform android --api_key <your_key> --file "../../Android/Legofy/app/build/outputs/apk/app-debug.apk" --notify "on" --groups "onlyme"```

**Comment by dac09** [comment]
Thanks!

**Comment by vrunoa** [comment]
:+1:
